// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27122018_AddTRANGTHAI_kien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27122018_AddTRANGTHAI_kien));
        
        string IMigrationMetadata.Id
        {
            get { return "201812270259080_27122018_AddTRANGTHAI_kien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
