// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190617_ADDTBL_TT188PL01_PL01TEMPLATE_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190617_ADDTBL_TT188PL01_PL01TEMPLATE_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201906170736068_20190617_ADDTBL_TT188PL01_PL01TEMPLATE_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
