// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _24072019_add_field_to_pha_b04_bctc_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24072019_add_field_to_pha_b04_bctc_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201907240809133_24072019_add_field_to_pha_b04_bctc_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
