// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190622_EDIT_TABLE_PHF_TIENDO_TUAN_THEMNAM_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190622_EDIT_TABLE_PHF_TIENDO_TUAN_THEMNAM_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201906220120154_20190622_EDIT_TABLE_PHF_TIENDO_TUAN_THEMNAM_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
