// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _03042019_ADD_TABLE_PHF_TT188_PL03_AND_PHF_TT188_PL03_TEMPLATE_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03042019_ADD_TABLE_PHF_TT188_PL03_AND_PHF_TT188_PL03_TEMPLATE_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201904030146534_03042019_ADD_TABLE_PHF_TT188_PL03_AND_PHF_TT188_PL03_TEMPLATE_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
