// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _28022019_ADD_TABLE_PHF_PL02_PL03_XLKN_CT_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28022019_ADD_TABLE_PHF_PL02_PL03_XLKN_CT_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201902281012405_28022019_ADD_TABLE_PHF_PL02_PL03_XLKN_CT_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
