// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _26082019_Add_3_table_B123_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26082019_Add_3_table_B123_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201908260856214_26082019_Add_3_table_B123_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
