// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _08102019_UPDATE_TABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08102019_UPDATE_TABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201910081012595_08102019_UPDATE_TABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
