// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _09112019_DUYTB_ADD_COLUMN_STTSAPXEP_PHB_B02BCTC_TEMPLATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09112019_DUYTB_ADD_COLUMN_STTSAPXEP_PHB_B02BCTC_TEMPLATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201911090313332_09112019_DUYTB_ADD_COLUMN_STTSAPXEP_PHB_B02BCTC_TEMPLATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
