// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11092019_UPDATE_COLUMN_PHF_HUONGDAN_CHIDAO_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11092019_UPDATE_COLUMN_PHF_HUONGDAN_CHIDAO_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201909110748464_11092019_UPDATE_COLUMN_PHF_HUONGDAN_CHIDAO_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
