// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DELETE_Required_2_TABLE_PHB_C_B06X_DETAIL_PHB_C_B06X_DUYTB_1911 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DELETE_Required_2_TABLE_PHB_C_B06X_DETAIL_PHB_C_B06X_DUYTB_1911));
        
        string IMigrationMetadata.Id
        {
            get { return "201911190318234_DELETE_Required_2_TABLE_PHB_C_B06X_DETAIL_PHB_C_B06X_DUYTB_1911"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
