// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _25112019_Add_COLUMN_SU_NGHIEP_TABLE_B121_B122_B123_B124_B125 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25112019_Add_COLUMN_SU_NGHIEP_TABLE_B121_B122_B123_B124_B125));
        
        string IMigrationMetadata.Id
        {
            get { return "201911250304204_25112019_Add_COLUMN_SU_NGHIEP_TABLE_B121_B122_B123_B124_B125"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
