// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddtblPHF_BM_07TT_TCDN_ThanhND : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddtblPHF_BM_07TT_TCDN_ThanhND));
        
        string IMigrationMetadata.Id
        {
            get { return "201901120243322_AddtblPHF_BM_07TT_TCDN_ThanhND"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
