// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191009_ADD_TABLE_PHF_DINHKEMFILE4_PHF_DINHKEMFILE5_PHF_DINHKEMFILE6_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191009_ADD_TABLE_PHF_DINHKEMFILE4_PHF_DINHKEMFILE5_PHF_DINHKEMFILE6_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "201910090233193_20191009_ADD_TABLE_PHF_DINHKEMFILE4_PHF_DINHKEMFILE5_PHF_DINHKEMFILE6_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
