// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _02122019_BO_REQUIRE_5TABLE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02122019_BO_REQUIRE_5TABLE));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060405103_02122019_BO_REQUIRE_5TABLE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
