// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191605_Add_TT129_PL03_04_05_06_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191605_Add_TT129_PL03_04_05_06_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201905160209049_20191605_Add_TT129_PL03_04_05_06_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
