// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190419_UPDATE_PHF_BM06_TONGHOP_PHANTICH_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190419_UPDATE_PHF_BM06_TONGHOP_PHANTICH_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201904190806264_20190419_UPDATE_PHF_BM06_TONGHOP_PHANTICH_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
