// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12052019_UPDATE_FIELD_KIENNGHI_CHITIET_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12052019_UPDATE_FIELD_KIENNGHI_CHITIET_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201905120755582_12052019_UPDATE_FIELD_KIENNGHI_CHITIET_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
