// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _09012018_ADD_PHF_BM_FILE_XLKN_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09012018_ADD_PHF_BM_FILE_XLKN_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090901115_09012018_ADD_PHF_BM_FILE_XLKN_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
