// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _23082019_add_15_tables_of_phb_pbdt_b1304_b1305_b1306_b1308_b14_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23082019_add_15_tables_of_phb_pbdt_b1304_b1305_b1306_b1308_b14_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201908230320598_23082019_add_15_tables_of_phb_pbdt_b1304_b1305_b1306_b1308_b14_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
