// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _21052019_ADDCOLUMN_THOIGIAN_TT188_TT08_TT129_Chungnh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21052019_ADDCOLUMN_THOIGIAN_TT188_TT08_TT129_Chungnh));
        
        string IMigrationMetadata.Id
        {
            get { return "201905210304015_21052019_ADDCOLUMN_THOIGIAN_TT188_TT08_TT129_Chungnh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
