// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _30082019_UPDATE_TALBE_PHF_NHAPBAOCAO_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_30082019_UPDATE_TALBE_PHF_NHAPBAOCAO_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201908300726435_30082019_UPDATE_TALBE_PHF_NHAPBAOCAO_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
