// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _23122019_ADD_COLUMN_PHF_DM_DOITUONG_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23122019_ADD_COLUMN_PHF_DM_DOITUONG_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201912230845077_23122019_ADD_COLUMN_PHF_DM_DOITUONG_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
