// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _06042019_editTablePHFTT188PL02_HieuDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06042019_editTablePHFTT188PL02_HieuDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201904060357304_06042019_editTablePHFTT188PL02_HieuDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
