// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _24062019_UPDATE_TABLE_PHF_DM_TCBC_TT03_BIEU01_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24062019_UPDATE_TABLE_PHF_DM_TCBC_TT03_BIEU01_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201906240418084_24062019_UPDATE_TABLE_PHF_DM_TCBC_TT03_BIEU01_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
