// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _23082019_UPDATE_LENGTH_PHB121_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_23082019_UPDATE_LENGTH_PHB121_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201908231039485_23082019_UPDATE_LENGTH_PHB121_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
