// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _05042019duyaddcolumdmnguon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05042019duyaddcolumdmnguon));
        
        string IMigrationMetadata.Id
        {
            get { return "201904050651024_05042019-duy-addcolum-dmnguon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
