// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191210_ADD_2_TABLE_PHB_L_PC_DT_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191210_ADD_2_TABLE_PHB_L_PC_DT_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100323108_20191210_ADD_2_TABLE_PHB_L_PC_DT_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
