// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _100602019_MODIFIELD_TABLE_PHF_KIENNGHI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_100602019_MODIFIELD_TABLE_PHF_KIENNGHI));
        
        string IMigrationMetadata.Id
        {
            get { return "201906100324366_100602019_MODIFIELD_TABLE_PHF_KIENNGHI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
