// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17072019_UPDATE_PHF_BIENBAN_LAMVIEC_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17072019_UPDATE_PHF_BIENBAN_LAMVIEC_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201907170822304_17072019_UPDATE_PHF_BIENBAN_LAMVIEC_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
