// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _06122019_DELETE_MA_CHUONG_DUY_TB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06122019_DELETE_MA_CHUONG_DUY_TB));
        
        string IMigrationMetadata.Id
        {
            get { return "201912060439334_06122019_DELETE_MA_CHUONG_DUY_TB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
