// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _10112019_ADD_COLUMN_PHB_B02BCQT_DETAIL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10112019_ADD_COLUMN_PHB_B02BCQT_DETAIL));
        
        string IMigrationMetadata.Id
        {
            get { return "201911100948133_10112019_ADD_COLUMN_PHB_B02BCQT_DETAIL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
