// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11112019_DUYTB_ADD_3_TABLE_PHB_B02_TT137 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11112019_DUYTB_ADD_3_TABLE_PHB_B02_TT137));
        
        string IMigrationMetadata.Id
        {
            get { return "201911110152353_11112019_DUYTB_ADD_3_TABLE_PHB_B02_TT137"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
