// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190520_AddTable_TT129_PL01A_01B_02_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190520_AddTable_TT129_PL01A_01B_02_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "201905200407294_20190520_AddTable_TT129_PL01A_01B_02_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
