// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27082019_alters_tables_phb_pbdt_b1501_b1502_change_table_name_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27082019_alters_tables_phb_pbdt_b1501_b1502_change_table_name_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201908280710134_27082019_alters_tables_phb_pbdt_b1501_b1502_change_table_name_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
