// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _09122019_ADD_BM14TT134 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09122019_ADD_BM14TT134));
        
        string IMigrationMetadata.Id
        {
            get { return "201912090958570_09122019_ADD_BM14TT134"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
