// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _28082019_UPDATE_TABLE_PHF_SOANTHAO_THANHTRA_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_28082019_UPDATE_TABLE_PHF_SOANTHAO_THANHTRA_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201908280419149_28082019_UPDATE_TABLE_PHF_SOANTHAO_THANHTRA_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
