// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190605_UPDATE_TABLE_TT129_THEMTENQUY_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190605_UPDATE_TABLE_TT129_THEMTENQUY_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201906050859197_20190605_UPDATE_TABLE_TT129_THEMTENQUY_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
