// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191118_update_2_table_BC_NHAPDT_XA_DETAIL_tuandx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191118_update_2_table_BC_NHAPDT_XA_DETAIL_tuandx));
        
        string IMigrationMetadata.Id
        {
            get { return "201911180946466_20191118_update_2_table_BC_NHAPDT_XA_DETAIL_tuandx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
