// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _02072019_ADD_PHB_B01_BSTT_2_DUNGNA : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02072019_ADD_PHB_B01_BSTT_2_DUNGNA));
        
        string IMigrationMetadata.Id
        {
            get { return "201907020944428_02072019_ADD_PHB_B01_BSTT_2_DUNGNA"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
