// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class THAY_DOI_TEN_TABLE_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(THAY_DOI_TEN_TABLE_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201911110818214_THAY_DOI_TEN_TABLE_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
