// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _06062019_ANHPT_DELETE_KIENNGHI_TAMGIU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06062019_ANHPT_DELETE_KIENNGHI_TAMGIU));
        
        string IMigrationMetadata.Id
        {
            get { return "201906060824131_06062019_ANHPT_DELETE_KIENNGHI_TAMGIU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
