// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _14012019_EdittblPHF_BM_08TT_TCDN_ThanhND2ND : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14012019_EdittblPHF_BM_08TT_TCDN_ThanhND2ND));
        
        string IMigrationMetadata.Id
        {
            get { return "201901141004258_14012019_EdittblPHF_BM_08TT_TCDN_ThanhND2ND"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
