// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _26082019_alter_detail_tables_of_phb_pbdt_b1307_b1309_b1310_b1311_b1312_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_26082019_alter_detail_tables_of_phb_pbdt_b1307_b1309_b1310_b1311_b1312_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201908260329331_26082019_alter_detail_tables_of_phb_pbdt_b1307_b1309_b1310_b1311_b1312_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
