// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190520_Delete_TBL_PHF_TT129_PL1A_1B_02_HieuDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190520_Delete_TBL_PHF_TT129_PL1A_1B_02_HieuDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201905200338467_20190520_Delete_TBL_PHF_TT129_PL1A_1B_02_HieuDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
