// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11102019_addFieldDVQHNS_kiennt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11102019_addFieldDVQHNS_kiennt));
        
        string IMigrationMetadata.Id
        {
            get { return "201910110239102_11102019_addFieldDVQHNS_kiennt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
