// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190712_UPDATE_TABLE_PHF_BM_FILE_CQHC_DVSN_TCDN_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190712_UPDATE_TABLE_PHF_BM_FILE_CQHC_DVSN_TCDN_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "201907120817241_20190712_UPDATE_TABLE_PHF_BM_FILE_CQHC_DVSN_TCDN_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
