// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _05032019_ADDTABLE_PHF_PL05_XLKN_CT_AND_PHF_PL05_XLKN_TEMPLATE_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05032019_ADDTABLE_PHF_PL05_XLKN_CT_AND_PHF_PL05_XLKN_TEMPLATE_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201903050200355_05032019_ADDTABLE_PHF_PL05_XLKN_CT_AND_PHF_PL05_XLKN_TEMPLATE_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
