// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _09112019_Add_Cloumn_PHB_B02BCQT_TEMPLATE_LAI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_09112019_Add_Cloumn_PHB_B02BCQT_TEMPLATE_LAI));
        
        string IMigrationMetadata.Id
        {
            get { return "201911090337331_09112019_Add_Cloumn_PHB_B02BCQT_TEMPLATE_LAI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
