// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _08032019_ADDTABLE_BAOCAO_PHF_TT03_BIEU1A_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08032019_ADDTABLE_BAOCAO_PHF_TT03_BIEU1A_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201903080403572_08032019_ADDTABLE_BAOCAO_PHF_TT03_BIEU1A_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
