// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _25072019_CREATE_TABLE_NHOMQUYEN_CHUCNANG_ANHPT_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25072019_CREATE_TABLE_NHOMQUYEN_CHUCNANG_ANHPT_));
        
        string IMigrationMetadata.Id
        {
            get { return "201907250542248_25072019_CREATE_TABLE_NHOMQUYEN_CHUCNANG_ANHPT_@"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
