// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190626_ADD3TBL_PHF_TIENDO_TTTUAN_TUAN_BAOCAO_HIEUDN : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190626_ADD3TBL_PHF_TIENDO_TTTUAN_TUAN_BAOCAO_HIEUDN));
        
        string IMigrationMetadata.Id
        {
            get { return "201906261102516_20190626_ADD3TBL_PHF_TIENDO_TTTUAN_TUAN_BAOCAO_HIEUDN"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
