// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _10072019_UPDATE_TABLE_BAOCAODONG_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_10072019_UPDATE_TABLE_BAOCAODONG_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201907101053404_10072019_UPDATE_TABLE_BAOCAODONG_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
