// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20082019_DUY_TB_ADD_3_BANG_B121_PBDT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20082019_DUY_TB_ADD_3_BANG_B121_PBDT));
        
        string IMigrationMetadata.Id
        {
            get { return "201908200242164_20082019_DUY_TB_ADD_3_BANG_B121_PBDT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
