// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _08072019_ADDCOLUMN_MACOT_BAOCAODONG_ANHPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08072019_ADDCOLUMN_MACOT_BAOCAODONG_ANHPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201907080946158_08072019_ADDCOLUMN_MACOT_BAOCAODONG_ANHPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
