// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _17052019_UpdateTable_KienNghi_TamGiu_AnhPT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17052019_UpdateTable_KienNghi_TamGiu_AnhPT));
        
        string IMigrationMetadata.Id
        {
            get { return "201905170823572_17052019_UpdateTable_KienNghi_TamGiu_AnhPT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
