// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20191108_update_table_PHB_PBDT_B111_Tuandx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20191108_update_table_PHB_PBDT_B111_Tuandx));
        
        string IMigrationMetadata.Id
        {
            get { return "201911080629012_20191108_update_table_PHB_PBDT_B111_Tuandx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
