// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _04032019_UPDATE_PHF_QD_PHEDUYET_THANHTRA_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_04032019_UPDATE_PHF_QD_PHEDUYET_THANHTRA_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201903040908376_04032019_UPDATE_PHF_QD_PHEDUYET_THANHTRA_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
