// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _22082019_add_6_tables_phb_pbdt_tt342_b1301_b1302_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22082019_add_6_tables_phb_pbdt_tt342_b1301_b1302_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201908220737045_22082019_add_6_tables_phb_pbdt_tt342_b1301_b1302_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
