// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _29062019_UPDATECOLUM_PHA_B03B_BCTC_REFID_tablePHA_B03B_BCTC_DETAIL_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_29062019_UPDATECOLUM_PHA_B03B_BCTC_REFID_tablePHA_B03B_BCTC_DETAIL_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201906290306216_29062019_UPDATECOLUM_PHA_B03B_BCTC_REFID_tablePHA_B03B_BCTC_DETAIL_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
