// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27082019_ADDTABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27082019_ADDTABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201908270215129_27082019_ADDTABLE_PHF_KHAIBAO_ND_THUCHIEN_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
