// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _15012018_ADD_TBL_PL02_XLKN_CT_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15012018_ADD_TBL_PL02_XLKN_CT_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201901150951436_15012018_ADD_TBL_PL02_XLKN_CT_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
