// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _15052019_ADD_TABLE_PHF_TT03_BIEU3C_TT_TEMPLATE_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15052019_ADD_TABLE_PHF_TT03_BIEU3C_TT_TEMPLATE_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201905151111323_15052019_ADD_TABLE_PHF_TT03_BIEU3C_TT_TEMPLATE_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
