// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _050819_fix_phb_sys_log_chuc_nang_dungna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_050819_fix_phb_sys_log_chuc_nang_dungna));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051007187_050819_fix_phb_sys_log_chuc_nang_dungna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
