// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _03072019_UPDATE_INT_TO_DECIMAL_B01_BTSS_1_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03072019_UPDATE_INT_TO_DECIMAL_B01_BTSS_1_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201907030333024_03072019_UPDATE_INT_TO_DECIMAL_B01_BTSS_1_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
