// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADD_COLUMN_STT_SAP_XEP_TABLE_PHB_C_B06X_DETAIL_19112019_DUYTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_COLUMN_STT_SAP_XEP_TABLE_PHB_C_B06X_DETAIL_19112019_DUYTB));
        
        string IMigrationMetadata.Id
        {
            get { return "201911191459215_ADD_COLUMN_STT_SAP_XEP_TABLE_PHB_C_B06X_DETAIL_19112019_DUYTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
