// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _20190916_UPDATE_TABLE_PHF_DM_BAOCAO_COLUMN_MA_PHONGBAN_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190916_UPDATE_TABLE_PHF_DM_BAOCAO_COLUMN_MA_PHONGBAN_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "201909160359404_20190916_UPDATE_TABLE_PHF_DM_BAOCAO_COLUMN_MA_PHONGBAN_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
