// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _15012019_DeleteCodePHF_BM_09TT_TCDN_ThanhND2th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15012019_DeleteCodePHF_BM_09TT_TCDN_ThanhND2th));
        
        string IMigrationMetadata.Id
        {
            get { return "201901150755386_15012019_DeleteCodePHF_BM_09TT_TCDN_ThanhND2th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
