// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addTbl_SYS_DVQHNS_QUANLY_kiennt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTbl_SYS_DVQHNS_QUANLY_kiennt));
        
        string IMigrationMetadata.Id
        {
            get { return "201911160451453_addTbl_SYS_DVQHNS_QUANLY_kiennt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
