// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADD_TBL_PHF_PL05_DANHSACHDONVI_08042019_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADD_TBL_PHF_PL05_DANHSACHDONVI_08042019_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201904081023004_ADD_TBL_PHF_PL05_DANHSACHDONVI_08042019_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
