// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27022019_UPDATETABLE_PHF_PL01_XLKN_TEMPLATE_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27022019_UPDATETABLE_PHF_PL01_XLKN_TEMPLATE_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201902270146164_27022019_UPDATETABLE_PHF_PL01_XLKN_TEMPLATE_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
