// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11122019_ADD_PHB_PBDT_TT344_B04_B05_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11122019_ADD_PHB_PBDT_TT344_B04_B05_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111053369_11122019_ADD_PHB_PBDT_TT344_B04_B05_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
