// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _27032019_UPDATE_PHF_TT03_BIEU1E_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27032019_UPDATE_PHF_TT03_BIEU1E_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "201903270902097_27032019_UPDATE_PHF_TT03_BIEU1E_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
