// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _16022019_AddThongTinNK_GTTTTTB_Duonghh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16022019_AddThongTinNK_GTTTTTB_Duonghh));
        
        string IMigrationMetadata.Id
        {
            get { return "201902131828431_16022019_AddThongTinNK_GTTTTTB_Duonghh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
