// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _15022020_UPDATE_DB_NONUMBER_PHF_KIENNGHI_TAMGIU_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_15022020_UPDATE_DB_NONUMBER_PHF_KIENNGHI_TAMGIU_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "202002150202021_15022020_UPDATE_DB_NONUMBER_PHF_KIENNGHI_TAMGIU_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
