// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _20200117_Add_2Colunm_table_PHF_GIAMSAT_DOAN_TT_TUANDX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200117_Add_2Colunm_table_PHF_GIAMSAT_DOAN_TT_TUANDX));
        
        string IMigrationMetadata.Id
        {
            get { return "202001170950095_20200117_Add_2Colunm_table_PHF_GIAMSAT_DOAN_TT_TUANDX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
