// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _07022020_UPDATE_DB_ADD_COLUMN_PHF_XD_KH_THANHTRA_BO_CHITIET_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_07022020_UPDATE_DB_ADD_COLUMN_PHF_XD_KH_THANHTRA_BO_CHITIET_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "202002070900518_07022020_UPDATE_DB_ADD_COLUMN_PHF_XD_KH_THANHTRA_BO_CHITIET_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
