// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _11022019_UPDATE_PHF_KIENNGHI_TAMGIU_VUDQ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11022019_UPDATE_PHF_KIENNGHI_TAMGIU_VUDQ));
        
        string IMigrationMetadata.Id
        {
            get { return "202002110225560_11022019_UPDATE_PHF_KIENNGHI_TAMGIU_VUDQ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
