// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _17012020_ADD_TABLE_PHF_BAOCAO_HANGTHANG_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17012020_ADD_TABLE_PHF_BAOCAO_HANGTHANG_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "202001170939024_17012020_ADD_TABLE_PHF_BAOCAO_HANGTHANG_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
