// <auto-generated />
namespace BTS.SP.API.ENTITY.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _14012020_ADD_COLUMN_TEN_DOITUONG_PHF_CAPNHAT_KETLUAN_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_14012020_ADD_COLUMN_TEN_DOITUONG_PHF_CAPNHAT_KETLUAN_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "202001140828452_14012020_ADD_COLUMN_TEN_DOITUONG_PHF_CAPNHAT_KETLUAN_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
