// <auto-generated />
namespace BTS.SP.AUTHENTICATION.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _27022020_ADDTABLE_DM_DBHC_CHUNGNH : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27022020_ADDTABLE_DM_DBHC_CHUNGNH));
        
        string IMigrationMetadata.Id
        {
            get { return "202002270846018_27022020_ADDTABLE_DM_DBHC_CHUNGNH"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
