// <auto-generated />
namespace BTS.SP.AUTHENTICATION.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initAuthDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initAuthDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202002241352155_initAuthDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
